// Generated by Wrangler on Thu Aug 22 2024 04:55:14 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	KV_SESSION: KVNamespace;
	NODE_VERSION: "20.16.0";
	PNPM_VERSION: "9.5.0";
	SESSION_COOKIE_SECRET: string;
	LOCAL: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	DB: D1Database;
}
