// Generated by Wrangler on Thu Aug 22 2024 04:09:20 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	NODE_VERSION: "20.16.0";
	PNPM_VERSION: "9.5.0";
	SESSION_COOKIE_SECRET: string;
	LOCAL: string;
}
