#:schema node_modules/wrangler/config-schema.json

name = "japanese-restream-web-system"
pages_build_output_dir = "./build/client"
compatibility_date = "2024-08-21"

[vars]
NODE_VERSION = "20.16.0"
PNPM_VERSION = "9.5.0"
